const WordList=[
        { word: "ocean",
             hint: "Large body of saltwater" },
        { word: "mountain", 
            hint: "A tall natural elevation of Earth's surface" },
        { word: "library", 
            hint: "A place where books are stored" },
        { word: "butterfly", 
            hint: "An insect with colorful wings" },
        { word: "rainbow", 
            hint: "A multicolored arc in the sky after rain" },
        { word: "moon",
             hint: "Earth's natural satellite" },
        { word: "sunflower",
             hint: "A tall plant with a large yellow flower" },
        { word: "clock", 
            hint: "A device used to measure time" },
        { word: "river", 
            hint: "A large natural stream of water" },
        { word: "desert",
             hint: "A dry area with little rainfall" },
        { word: "volcano", 
            hint: "A mountain that erupts molten rock" },
        { word: "mirror",
             hint: "Reflects your image" },
        { word: "eagle", 
            hint: "A bird of prey" },
        { word: "candle", 
            hint: "A stick of wax that burns for light" },
        { word: "bridge", 
            hint: "A structure that spans across water or land" },
        { word: "guitar",
             hint: "A musical instrument with strings" },
        { word: "forest", 
            hint: "A dense collection of trees" },
        { word: "camera", 
            hint: "A device for taking photographs" },
        { word: "compass",
             hint: "Used to find directions" },
        { word: "pyramid",
             hint: "A triangular structure from ancient Egypt" },
        { word: "lighthouse",
             hint: "Guides ships at sea" },
        { word: "island", 
            hint: "Land surrounded by water" },
        { word: "snowflake",
             hint: "A single ice crystal" },
        { word: "bicycle", 
            hint: "A two-wheeled vehicle" },
        { word: "planet", 
            hint: "A celestial body orbiting a star" },
        { word: "castle", 
            hint: "A large fortified residence" },
        { word: "penguin", 
            hint: "A flightless bird found in cold regions" },
        { word: "jungle", 
            hint: "A dense tropical forest" },
        { word: "telescope", 
            hint: "Used to observe distant objects in space" },
        { word: "flamingo", 
            hint: "A pink wading bird" },
        { word: "windmill", 
            hint: "Converts wind energy into power" },
        { word: "diamond",
             hint: "A precious gemstone" },
        { word: "rose", 
            hint: "A fragrant flower with thorns" },
        { word: "train", 
            hint: "A vehicle that runs on tracks" },
        { word: "starfish",
             hint: "A marine animal with arms" },
        { word: "rocket", 
            hint: "A vehicle for space travel" },
        { word: "lantern", 
            hint: "A portable light source" },
        { word: "cactus",
             hint: "A plant that grows in deserts" },
        { word: "parrot", 
            hint: "A colorful talking bird" },
        { word: "helmet", 
            hint: "Protects your head" },
        { word: "kite", 
            hint: "Flies in the wind on a string" },
        { word: "dragon",
             hint: "A mythical fire-breathing creature" },
        { word: "violin",
             hint: "A stringed musical instrument" },
        { word: "coconut",
             hint: "A tropical fruit with a hard shell" },
        { word: "spider", 
            hint: "A web-spinning arachnid" },
        { word: "pirate", 
            hint: "A person who robs ships" },
        { word: "umbrella", 
            hint: "Protects from rain or sun" },
        { word: "waterfall",
             hint: "Water flowing over a steep drop" },
        { word: "anchor", 
            hint: "Keeps a ship in place" },
        { word: "igloo",
             hint: "A house made of ice blocks" },
        { word: "balloon",
             hint: "Filled with air or gas" },
        { word: "scissors",
             hint: "Used for cutting" },
        { word: "vase",
             hint: "Holds flowers" },
        { word: "lemon",
             hint: "A sour yellow fruit" },
        { word: "globe",
             hint: "A spherical model of Earth" },
        { word: "swan", 
            hint: "A graceful white bird" },
        { word: "turtle", 
            hint: "A slow-moving reptile with a shell" },
        { word: "firework",
             hint: "Creates colorful explosions in the sky" },
        { word: "iceberg", 
            hint: "A large piece of floating ice" },
        { word: "cupcake",
             hint: "A small sweet cake" },
        { word: "octopus",
             hint: "A sea creature with eight arms" },
        { word: "zebra", 
            hint: "A striped black-and-white animal" },
        { word: "ferris Wheel", 
            hint: "An amusement park ride" },
        { word: "suitcase",
             hint: "Used for carrying clothes while traveling" },
        { word: "football",
             hint: "A game played with a round ball" },
        { word: "treasure",
             hint: "Hidden or valuable riches" },
        { word: "chocolate",
             hint: "A sweet treat made from cocoa" },
        { word: "chair", 
            hint: "A piece of furniture for sitting" },
        { word: "horse", 
            hint: "An animal used for riding" },
        { word: "crown",
             hint: "Worn by kings or queens" },
        { word: "apple",
             hint: "A common red or green fruit" },
        { word: "ship",
             hint: "A large water vessel" },
        { word: "glasses", 
            hint: "Helps you see better" },
        { word: "laptop",
             hint: "A portable computer" },
        { word: "painting", 
            hint: "A picture made with paint" }
      ];
      
    